export const PLAYGROUND_LANGUAGE = {
	"apiKey.required.tr": "API Anahtarı Gerekli",
	"apiKey.required.en": "API Key Required",
	"apiKey.required.de": "API-Schlüssel erforderlich",
	"apiKey.required.sv": "API-nyckel krävs",
	"apiKey.required.ru": "Требуется API-ключ",
	"apiKey.required.es": "Se requiere clave API",
	"action.transcreating.tr": "Mesajını hazırlıyorum...",
	"action.transcreating.en": "Crafting your message...",
	"action.transliterating.tr": "Okunabilir hale getiriyorum...",
	"action.transliterating.en": "Making it easy to read...",
	"action.tts.tr": "Sesini oluşturuyorum...",
	"action.tts.en": "Creating your voice...",
	"action.gamifying.tr": "Mesajını oyunlaştırıyorum...",
	"action.gamifying.en": "Gamifying your message...",
	"description.start.tr": "Sesini duymaya hazırım",
	"description.start.en": "Ready to hear your voice",
	"description.stopRecording.tr": "Tamam mı? Bitirmek için dokun",
	"description.stopRecording.en": "Got everything? Tap to finish",
	"description.processing.tr": "Bir saniye...",
	"description.processing.en": "Just a moment...",
	"description.crafting.tr": "Neredeyse hazır...",
	"description.crafting.en": "Almost there...",
	"description.pronunciation.tr": "Mükemmel olsun...",
	"description.pronunciation.en": "Making it sound perfect...",
	"description.generating.tr": "Son dokunuşlar...",
	"description.generating.en": "Adding the final touch...",
	"description.play.tr": "Hadi dinleyelim",
	"description.play.en": "Let's hear it",
	"description.pause.tr": "Ara verelim",
	"description.pause.en": "Take a break",
	"content.welcome.tr": "Dil yolculuğuna başlamak için katıl",
	"content.welcome.en": "Join us to start your language journey",
	"content.start.tr": "Hazır olduğunda kırmızı butona dokun",
	"content.start.en": "Tap the button when you're ready",
	"content.listening.tr": "Dinliyorum...",
	"content.listening.en": "All ears...",
	"content.converting.tr": "Üzerinde çalışıyorum...",
	"content.converting.en": "Working on it...",
	"content.tapMic.tr": "Tamam mı? Bitirmek için dokun",
	"content.tapMic.en": "Got it? Tap to finish",
	"content.wait.tr": "Neredeyse hazır...",
	"content.wait.en": "Almost there...",
	"content.pronunciation.tr": "Nasıl söylenir",
	"content.pronunciation.en": "How to say it",
	"content.listen.tr": "Mesajını dinle",
	"content.listen.en": "Hear your message",
	"content.gameMode.tr": "Oyun Modu",
	"content.gameMode.en": "Game Mode",
	"content.textTooLong.tr": "Metin çok uzun",
	"content.textTooLong.en": "Text too long",
	"content.simpleView.tr": "Basit Görünüm",
	"content.simpleView.en": "Simple View",
	"content.confirmClipboard.tr": "Metni işlemek için dokun",
	"content.confirmClipboard.en": "Tap to process text",
	"history.title.tr": "Yolculuğun",
	"history.title.en": "Your Journey",
	"history.items.tr": "anı",
	"history.items.en": "memories",
	"history.text.tr": "metin",
	"history.text.en": "text",
	"history.select.tr": "Seç",
	"history.select.en": "Select",
	"history.selected.tr": "seçildi",
	"history.selected.en": "selected",
	"history.deleteSelected.tr": "Seçilenleri Sil",
	"history.deleteSelected.en": "Delete Selected",
	"history.cancelSelection.tr": "İptal",
	"history.cancelSelection.en": "Cancel",
	"history.show.tr": "Göster",
	"history.show.en": "Show",
	"history.hide.tr": "Gizle",
	"history.hide.en": "Hide",
	"history.original.tr": "Senin sözlerin",
	"history.original.en": "Your words",
	"history.translation.tr": "Yeni haliyle",
	"history.translation.en": "In new words",
	"history.pronunciation.tr": "Nasıl söylenir",
	"history.pronunciation.en": "How to say it",
	"history.search.tr": "Anılarını bul...",
	"history.search.en": "Find your moments...",
	"history.showMore.tr": "Daha fazla anı",
	"history.showMore.en": "More memories",
	"history.remaining.tr": "tane daha",
	"history.remaining.en": "more items",
	"history.confirmDelete.tr": "Silmeyi Onayla",
	"history.confirmDelete.en": "Confirm Deletion",
	"history.deleteWarning.tr":
		"Bu işlem geri alınamaz. Seçilen öğeler kalıcı olarak silinecek.",
	"history.deleteWarning.en":
		"This action cannot be undone. Selected items will be permanently deleted.",
	"history.deletingOneItem.tr": "1 öğe silinecek:",
	"history.deletingOneItem.en": "1 item will be deleted:",
	"history.deletingMultipleItems.tr": "{count} öğe silinecek:",
	"history.deletingMultipleItems.en":
		"{count} items will be deleted:",
	"history.untitled.tr": "İsimsiz öğe",
	"history.untitled.en": "Untitled item",
	"cancel.tr": "İptal",
	"cancel.en": "Cancel",
	"settings.speed.tr": "Ses Hızı",
	"settings.speed.en": "Speech Speed",
	"time.minute.tr": "d",
	"time.minute.en": "m",
	"time.hour.tr": "s",
	"time.hour.en": "h",
	"time.day.tr": "g",
	"time.day.en": "d",
	"time.ago.tr": "önce",
	"time.ago.en": "ago",
	"time.invalid.tr": "Geçersiz tarih",
	"time.invalid.en": "Invalid date",
	"private.enter.tr": "Gizli Moda Geç",
	"private.enter.en": "Enter Private Mode",
	"private.exit.tr": "Gizli Moddan Çık",
	"private.exit.en": "Exit Private Mode",
	"private.description.tr":
		"Sadece anonim olarak gelişmene yardımcı oluyoruz",
	"private.description.en": "We only track your progress anonymously",
	"private.save.tr": "Gelişimini kaydet",
	"private.save.en": "Save your progress",
	"private.noSave.tr": "Kimliğin gizli, gelişimin bizimle",
	"private.noSave.en":
		"Your identity is private, your progress is with us",
	"noResults.tr": "Sonuç bulunamadı",
	"noResults.en": "No results found",
	"confirmDelete.tr": "Silmeyi onayla",
	"confirmDelete.en": "Confirm delete",
	"delete.tr": "Sil",
	"delete.en": "Delete",
	"loadToPlayground.tr": "Oyun alanına yükle",
	"loadToPlayground.en": "Load to playground",
	"share.tr": "Paylaş",
	"share.en": "Share",
	"gameLoading.tr": "Oyun hazırlanıyor...",
	"gameLoading.en": "Loading game...",
	"playground.title.tr": "Oyun Alanı",
	"playground.title.en": "Playground",
	"error.auth.signIn.tr": "Giriş yapılamadı",
	"error.auth.signIn.en": "Failed to sign in",
	"error.auth.signOut.tr": "Çıkış yapılamadı",
	"error.auth.signOut.en": "Failed to sign out",
	"error.auth.userNotFound.tr": "Kullanıcı bulunamadı",
	"error.auth.userNotFound.en": "User not found",

	// Preferences Errors
	"error.preferences.update.tr": "Tercihler güncellenemedi",
	"error.preferences.update.en": "Failed to update preferences",

	// History Errors
	"error.history.add.tr": "Geçmiş eklenemedi",
	"error.history.add.en": "Failed to add history",
	"error.history.update.tr": "Geçmiş güncellenemedi",
	"error.history.update.en": "Failed to update history",
	"error.history.delete.tr": "Geçmiş silinemedi",
	"error.history.delete.en": "Failed to delete history",

	// API Errors
	"error.api.transcribe.tr": "Ses metne dönüştürülemedi",
	"error.api.transcribe.en": "Failed to transcribe audio",
	"error.api.translate.tr": "Çeviri oluşturulamadı",
	"error.api.translate.en": "Failed to create translation",
	"error.api.segmentedTranslate.tr": "Bölümlü çeviri oluşturulamadı",
	"error.api.segmentedTranslate.en":
		"Failed to create segmented translation",
	"error.api.transliterate.tr": "Transliterasyon oluşturulamadı",
	"error.api.transliterate.en": "Failed to create transliteration",
	"error.api.tts.tr": "Metin sese dönüştürülemedi",
	"error.api.tts.en": "Failed to convert text to speech",
	"error.api.segmentate.tr": "Metin bölümlenemedi",
	"error.api.segmentate.en": "Failed to segmentate text",
	"error.api.transcreate.tr": "Transcreation oluşturulamadı",
	"error.api.transcreate.en": "Failed to create transcreation",

	// Lookup Sheet
	"lookup.aiWarning.tr":
		"AI çevirileri her zaman doğru değildir. Lütfen doğrulamayı kontrol edin.",
	"lookup.aiWarning.en":
		"AI translations are not always accurate. Please verify the translation before using it.",

	// Russian translations
	"action.transcreating.ru": "Готовлю ваше сообщение...",
	"action.transliterating.ru": "Делаю удобочитаемым...",
	"action.tts.ru": "Создаю ваш голос...",
	"action.gamifying.ru": "Геймифицирую ваше сообщение...",
	"description.start.ru": "Готов услышать ваш голос",
	"description.stopRecording.ru": "Готово? Нажмите, чтобы закончить",
	"description.processing.ru": "Момент...",
	"description.crafting.ru": "Почти готово...",
	"description.pronunciation.ru": "Делаю произношение идеальным...",
	"description.generating.ru": "Последние штрихи...",
	"description.play.ru": "Давайте послушаем",
	"description.pause.ru": "Сделаем паузу",
	"content.welcome.ru":
		"Присоединяйтесь, чтобы начать языковое путешествие",
	"content.start.ru": "Когда будете готовы, нажмите красную кнопку",
	"content.listening.ru": "Слушаю...",
	"content.converting.ru": "Работаю над этим...",
	"content.tapMic.ru": "Готово? Нажмите, чтобы закончить",
	"content.wait.ru": "Почти готово...",
	"content.pronunciation.ru": "Как произносится",
	"content.listen.ru": "Прослушайте свое сообщение",
	"content.gameMode.ru": "Игровой режим",
	"content.textTooLong.ru": "Текст слишком длинный",
	"content.simpleView.ru": "Простой вид",
	"content.confirmClipboard.ru": "Нажмите, чтобы обработать текст",
	"history.title.ru": "Ваш путь",
	"history.items.ru": "воспоминания",
	"history.text.ru": "текст",
	"history.select.ru": "Выбрать",
	"history.selected.ru": "выбрано",
	"history.deleteSelected.ru": "Удалить выбранные",
	"history.cancelSelection.ru": "Отмена",
	"history.show.ru": "Показать",
	"history.hide.ru": "Скрыть",
	"history.original.ru": "Ваши слова",
	"history.translation.ru": "В новом виде",
	"history.pronunciation.ru": "Как произносится",
	"history.search.ru": "Найти свои моменты...",
	"history.showMore.ru": "Больше воспоминаний",
	"history.remaining.ru": "еще",
	"history.confirmDelete.ru": "Подтвердить удаление",
	"history.deleteWarning.ru":
		"Это действие необратимо. Выбранные элементы будут удалены навсегда.",
	"history.deletingOneItem.ru": "1 элемент будет удален:",
	"history.deletingMultipleItems.ru":
		"{count} элементов будет удалено:",
	"history.untitled.ru": "Безымянный элемент",
	"cancel.ru": "Отмена",
	"settings.speed.ru": "Скорость речи",
	"time.minute.ru": "м",
	"time.hour.ru": "ч",
	"time.day.ru": "д",
	"time.ago.ru": "назад",
	"time.invalid.ru": "Неверная дата",
	"private.enter.ru": "Войти в приватный режим",
	"private.exit.ru": "Выйти из приватного режима",
	"private.description.ru":
		"Мы отслеживаем ваш прогресс только анонимно",
	"private.save.ru": "Сохранить прогресс",
	"private.noSave.ru": "Ваша личность скрыта, прогресс с нами",
	"noResults.ru": "Результатов не найдено",
	"confirmDelete.ru": "Подтвердить удаление",
	"delete.ru": "Удалить",
	"loadToPlayground.ru": "Загрузить в песочницу",
	"share.ru": "Поделиться",
	"gameLoading.ru": "Игра загружается...",
	"playground.title.ru": "Песочница",
	"error.auth.signIn.ru": "Не удалось войти",
	"error.auth.signOut.ru": "Не удалось выйти",
	"error.auth.userNotFound.ru": "Пользователь не найден",
	"error.preferences.update.ru": "Не удалось обновить настройки",
	"error.history.add.ru": "Не удалось добавить в историю",
	"error.history.update.ru": "Не удалось обновить историю",
	"error.history.delete.ru": "Не удалось удалить из истории",
	"error.api.transcribe.ru": "Не удалось транскрибировать аудио",
	"error.api.translate.ru": "Не удалось создать перевод",
	"error.api.segmentedTranslate.ru":
		"Не удалось создать сегментированный перевод",
	"error.api.transliterate.ru": "Не удалось создать транслитерацию",
	"error.api.tts.ru": "Не удалось преобразовать текст в речь",
	"error.api.segmentate.ru": "Не удалось сегментировать текст",
	"error.api.transcreate.ru": "Не удалось создать транс-креацию",
	"lookup.aiWarning.ru":
		"AI-переводы не всегда точны. Пожалуйста, проверьте перевод перед использованием.",
	"playground.aiWarning.tr":
		"Yapay zeka da insanlar gibi öğreniyor, bazen hata yapabilir",
	"playground.aiWarning.en":
		"AI learns like humans, sometimes it makes mistakes",
	"playground.aiWarning.ru":
		"AI-переводы не всегда точны. Пожалуйста, проверьте перевод перед использованием.",
} as const
