export const AUTH_LANGUAGE = {
	// Brand
	"auth.brand.title.tr": "TransLearn AI",
	"auth.brand.title.en": "TransLearn AI",
	"auth.brand.subtitle.tr": "AI ile Öğrenmeyi Dönüştür",
	"auth.brand.subtitle.en": "Transform Learning with AI",

	// Hero
	"auth.hero.title.tr": "Kendi Sesinle, Kendi Kelimelerinle İngilizceyi Keşfet",
	"auth.hero.title.en": "Discover English with Your Own Voice, Your Own Words",
	"auth.hero.description.tr": "Ben sana başkalarının kelimeleriyle değil, kendi dünyanla İngilizce öğrenmenin ne hissettirdiğini göstermek istiyorum.",
	"auth.hero.description.en": "I want to show you what it feels like to learn English not with other people's words, but with your own world.",

	// CTA Buttons
	"auth.cta.start.tr": "Hemen Başla",
	"auth.cta.start.en": "Get Started",
	"auth.cta.signing.tr": "Giriş yapılıyor...",
	"auth.cta.signing.en": "Signing in...",
	"auth.cta.howItWorks.tr": "Nasıl Çalışıyor?",
	"auth.cta.howItWorks.en": "How Does It Work?",
	"auth.cta.continueGoogle.tr": "Google ile Devam Et",
	"auth.cta.continueGoogle.en": "Continue with Google",

	// Features
	"auth.feature1.title.tr": "Kendini Anlatmanın Yeni Yolu",
	"auth.feature1.title.en": "A New Way to Express Yourself",
	"auth.feature1.description.tr": "Bu, kurallarla sıkıştırılan bir dil öğrenme yöntemi değil. Bu, kendini nasıl ifade edebileceğini deneyimleyerek keşfetmen için bir alan.",
	"auth.feature1.description.en": "This is not a language learning method constrained by rules. This is a space for you to discover how you can express yourself through experience.",

	"auth.feature2.title.tr": "Nasıl Hissettirdiğini Keşfet",
	"auth.feature2.title.en": "Discover How It Feels",
	"auth.feature2.description.tr": "Konuşurken kendi kelimelerini duymak nasıl bir his olurdu? İlk defa kendi sesinle İngilizce düşünmek, dinlemek, kendi düşüncelerini İngilizce anlatmak...",
	"auth.feature2.description.en": "What would it feel like to hear your own words while speaking? For the first time, thinking in English with your own voice, listening, expressing your own thoughts in English...",

	"auth.feature3.title.tr": "Deneyimle ve Hisset",
	"auth.feature3.title.en": "Experience and Feel",
	"auth.feature3.description.tr": "Bunu hissettiğin an, öğrenme zorunluluk olmaktan çıkar. Çünkü artık İngilizce senin için sadece bir ders değil, kendini anlatmanın yeni bir yolu.",
	"auth.feature3.description.en": "The moment you feel this, learning stops being an obligation. Because now English is not just a lesson for you, but a new way to express yourself.",

	// API Key Components
	"apikey.gate.required.tr": "Bu özelliği kullanmak için API anahtarları gerekli",
	"apikey.gate.required.en": "API keys required to use this feature",
	"apikey.gate.configure.tr": "API Anahtarlarını Yapılandır",
	"apikey.gate.configure.en": "Configure API Keys",
	"apikey.gate.loading.tr": "Yükleniyor...",
	"apikey.gate.loading.en": "Loading...",

	"apikey.setup.title.tr": "API Yapılandırması",
	"apikey.setup.title.en": "API Configuration",
	"apikey.setup.description.tr": "TransLearn kendi API anahtarlarınızı gerektirir. Anahtarlarınız şifrelenir ve hiçbir zaman paylaşılmaz.",
	"apikey.setup.description.en": "TransLearn requires your own API keys to function. Your keys are encrypted and never shared.",
	"apikey.setup.openai.label.tr": "OpenAI API Anahtarı",
	"apikey.setup.openai.label.en": "OpenAI API Key",
	"apikey.setup.openai.description.tr": "Transkripsiyon ve AI özellikleri için gerekli",
	"apikey.setup.openai.description.en": "Required for transcription and AI features",
	"apikey.setup.elevenlabs.label.tr": "ElevenLabs API Anahtarı",
	"apikey.setup.elevenlabs.label.en": "ElevenLabs API Key",
	"apikey.setup.elevenlabs.description.tr": "Yüksek kaliteli metinden sese dönüştürme için",
	"apikey.setup.elevenlabs.description.en": "For high-quality text-to-speech",
	"apikey.setup.voiceid.label.tr": "ElevenLabs Ses ID",
	"apikey.setup.voiceid.label.en": "ElevenLabs Voice ID",
	"apikey.setup.voiceid.description.tr": "İsteğe bağlı: Metinden sese dönüştürme için özel ElevenLabs sesinizi kullanın",
	"apikey.setup.voiceid.description.en": "Optional: Use your custom ElevenLabs voice for text-to-speech",
	"apikey.setup.configured.tr": "Yapılandırıldı",
	"apikey.setup.configured.en": "Configured",
	"apikey.setup.optional.tr": "İsteğe bağlı",
	"apikey.setup.optional.en": "Optional",
	"apikey.setup.getkey.tr": "API Anahtarı Al →",
	"apikey.setup.getkey.en": "Get API Key →",
	"apikey.setup.findvoice.tr": "Ses ID Bul →",
	"apikey.setup.findvoice.en": "Find Voice ID →",
	"apikey.setup.save.tr": "Anahtarları Kaydet",
	"apikey.setup.save.en": "Save Keys",
	"apikey.setup.saving.tr": "Kaydediliyor...",
	"apikey.setup.saving.en": "Saving...",
	"apikey.setup.cancel.tr": "İptal",
	"apikey.setup.cancel.en": "Cancel",
	"apikey.setup.success.tr": "API anahtarları başarıyla kaydedildi",
	"apikey.setup.success.en": "API keys saved successfully",
	"apikey.setup.error.tr": "API anahtarları kaydedilemedi",
	"apikey.setup.error.en": "Failed to save API keys",
	"apikey.setup.nochanges.tr": "Kaydedilecek değişiklik yok",
	"apikey.setup.nochanges.en": "No changes to save",
} as const